### ISSUE TITLE
SHA-1: a448f1b03249ec3c050c15bbaf47e0699c969ad8

### ISSUE THREAD

**Issue by gdut-yy** [gdut-yy/OnJava8-zh#1]
SHA-1: a448f1b03249ec3c050c15bbaf47e0699c969ad8 Dec 18, 2019

**Comment by sjsdfg** [comment]
.......请标明来源

**Comment by gdut-yy** [comment]
fixed by f2f574e18d9b6306827501ef679bd34b73f700e6

感谢原作！本翻译来源 repo 地址：https://github.com/LingCoder/OnJava8
